spring:
  datasource:
    url: jdbc:postgresql://10.178.0.8:5432/owoonan
    username: postgresql
    password: postgrespassword

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        defalt_batch_fetch_size: 100
