spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/owoonan
    username: postgres
    password: postgres

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        defalt_batch_fetch_size: 100

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace